
/* ============================================================
SECTION 1: INNER JOIN & LEFT JOIN (Q1–Q15)
============================================================ */

/* -----------------------------
Q1. Customer Order Summary

Problem:
Generate a report showing each customer along with the total number
of orders they have placed.
------------------------------*/

-- Solution 1: LEFT JOIN

SELECT c.customer_id,
       c.name,
       COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
       ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name;

-- Solution 2: Correlated Subquery

SELECT c.customer_id,
       c.name,
       (SELECT COUNT(*)
          FROM orders o
         WHERE o.customer_id = c.customer_id) AS total_orders
FROM customers c;

/*
Interview Note:
LEFT JOIN + GROUP BY is most common.
Correlated subquery demonstrates another approach.
*/


/* -----------------------------
Q2. Customers Who Never Placed an Order

Problem:
Identify customers who have never placed an order.
------------------------------*/

-- Solution 1: LEFT JOIN

SELECT c.customer_id,
       c.name
FROM customers c
LEFT JOIN orders o
       ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- Solution 2: NOT EXISTS

SELECT c.customer_id,
       c.name
FROM customers c
WHERE NOT EXISTS (
      SELECT 1
      FROM orders o
      WHERE o.customer_id = c.customer_id
);

/*
Interview Note:
NOT EXISTS is generally preferred for anti-join scenarios.
*/


/* -----------------------------
Q3. Revenue by City

Problem:
Calculate total revenue generated by customers from each city.
------------------------------*/

-- Solution 1

SELECT c.city,
       SUM(o.order_value) AS total_revenue
FROM customers c
JOIN orders o
     ON c.customer_id = o.customer_id
GROUP BY c.city;

-- Solution 2

SELECT city,
       SUM(order_value) AS total_revenue
FROM (
      SELECT c.city,
             o.order_value
      FROM customers c
      JOIN orders o
           ON c.customer_id = o.customer_id
)
GROUP BY city;

/*
Interview Note:
First approach is cleaner and preferred.
*/


/* -----------------------------
Q4. Revenue by Gender

Problem:
Find total revenue generated by each gender segment.
------------------------------*/

-- Solution 1

SELECT c.gender,
       SUM(o.order_value) AS total_revenue
FROM customers c
JOIN orders o
     ON c.customer_id = o.customer_id
GROUP BY c.gender;

-- Solution 2

SELECT gender,
       SUM(order_value)
FROM (
      SELECT c.gender,
             o.order_value
      FROM customers c
      JOIN orders o
           ON c.customer_id = o.customer_id
)
GROUP BY gender;


/* -----------------------------
Q5. Revenue by Product Category

Problem:
Calculate revenue generated by each product category.
------------------------------*/

-- Solution 1

SELECT p.category,
       SUM(s.quantity * p.price) AS revenue
FROM products p
JOIN sales s
     ON p.product_id = s.product_id
GROUP BY p.category;

-- Solution 2

SELECT category,
       SUM(revenue) AS revenue
FROM (
      SELECT p.category,
             s.quantity * p.price AS revenue
      FROM products p
      JOIN sales s
           ON p.product_id = s.product_id
)
GROUP BY category;


/* -----------------------------
Q6. Unsold Products

Problem:
Find products that have never been sold.
------------------------------*/

-- Solution 1: LEFT JOIN

SELECT p.product_id,
       p.name
FROM products p
LEFT JOIN sales s
       ON p.product_id = s.product_id
WHERE s.product_id IS NULL;

-- Solution 2: NOT EXISTS

SELECT p.product_id,
       p.name
FROM products p
WHERE NOT EXISTS (
      SELECT 1
      FROM sales s
      WHERE s.product_id = p.product_id
);

/*
Interview Note:
A very common interview question.
Know both approaches.
*/


/* -----------------------------
Q7. Products Never Ordered in Last 30 Days

Problem:
Identify products that have not been purchased in the last 30 days.
------------------------------*/

-- Solution 1

SELECT p.product_id,
       p.name
FROM products p
LEFT JOIN customer_orders_history h
       ON p.product_id = h.product_id
      AND h.order_date >= SYSDATE - 30
WHERE h.product_id IS NULL;

-- Solution 2

SELECT p.product_id,
       p.name
FROM products p
WHERE NOT EXISTS (
      SELECT 1
      FROM customer_orders_history h
      WHERE h.product_id = p.product_id
      AND h.order_date >= SYSDATE - 30
);


/* -----------------------------
Q8. Total Quantity Sold Per Product

Problem:
Calculate total quantity sold for every product.
------------------------------*/

-- Solution 1

SELECT p.product_id,
       p.name,
       SUM(s.quantity) AS total_quantity
FROM products p
JOIN sales s
     ON p.product_id = s.product_id
GROUP BY p.product_id, p.name;

-- Solution 2

SELECT product_id,
       SUM(quantity) AS total_quantity
FROM sales
GROUP BY product_id;


/* -----------------------------
Q9. Customers Who Purchased Electronics

Problem:
Find customers who purchased products from the Electronics category.
------------------------------*/

-- Solution 1

SELECT DISTINCT c.customer_id,
                c.name
FROM customers c
JOIN customer_orders_history h
     ON c.customer_id = h.customer_id
JOIN products p
     ON h.product_id = p.product_id
WHERE p.category = 'Electronics';

-- Solution 2: EXISTS

SELECT c.customer_id,
       c.name
FROM customers c
WHERE EXISTS (
      SELECT 1
      FROM customer_orders_history h
      JOIN products p
           ON h.product_id = p.product_id
      WHERE h.customer_id = c.customer_id
      AND p.category = 'Electronics'
);


/* -----------------------------
Q10. Customers Who Bought More Than One Product

Problem:
Identify customers who purchased more than one distinct product.
------------------------------*/

-- Solution 1

SELECT c.customer_id,
       c.name,
       COUNT(DISTINCT h.product_id) AS product_count
FROM customers c
JOIN customer_orders_history h
     ON c.customer_id = h.customer_id
GROUP BY c.customer_id, c.name
HAVING COUNT(DISTINCT h.product_id) > 1;

-- Solution 2

SELECT customer_id
FROM customer_orders_history
GROUP BY customer_id
HAVING COUNT(DISTINCT product_id) > 1;


/* -----------------------------
Q11. Orders With Customer Details

Problem:
Display all orders along with customer information.
------------------------------*/

-- Solution 1

SELECT o.order_id,
       o.order_date,
       o.order_value,
       c.name,
       c.city
FROM orders o
JOIN customers c
     ON o.customer_id = c.customer_id;

-- Solution 2

SELECT *
FROM orders o
NATURAL JOIN (
      SELECT customer_id,
             name,
             city
      FROM customers
);

/*
Interview Note:
Explicit JOIN is preferred.
Avoid NATURAL JOIN in production.
*/


/* -----------------------------
Q12. Products With Sales Count

Problem:
Find how many orders each product appeared in.
------------------------------*/

-- Solution 1

SELECT p.product_id,
       p.name,
       COUNT(s.order_id) AS sales_count
FROM products p
LEFT JOIN sales s
       ON p.product_id = s.product_id
GROUP BY p.product_id, p.name;

-- Solution 2

SELECT product_id,
       COUNT(order_id) AS sales_count
FROM sales
GROUP BY product_id;


/* -----------------------------
Q13. Customers With Latest Order Date

Problem:
Find the most recent order date for each customer.
------------------------------*/

-- Solution 1

SELECT c.customer_id,
       c.name,
       MAX(o.order_date) AS latest_order_date
FROM customers c
LEFT JOIN orders o
       ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name;

-- Solution 2

SELECT customer_id,
       MAX(order_date) AS latest_order_date
FROM orders
GROUP BY customer_id;


/* -----------------------------
Q14. Revenue Generated by Active Customers

Problem:
Calculate total revenue generated by active customers.
------------------------------*/

-- Solution 1

SELECT SUM(o.order_value) AS revenue
FROM customers c
JOIN orders o
     ON c.customer_id = o.customer_id
WHERE c.is_active = 'Y';

-- Solution 2

SELECT SUM(order_value)
FROM orders
WHERE customer_id IN (
      SELECT customer_id
      FROM customers
      WHERE is_active = 'Y'
);


/* -----------------------------
Q15. Customers With No Purchases This Year

Problem:
Find customers who have not made a purchase during the current year.
------------------------------*/

-- Solution 1

SELECT c.customer_id,
       c.name
FROM customers c
LEFT JOIN orders o
       ON c.customer_id = o.customer_id
      AND EXTRACT(YEAR FROM o.order_date) =
          EXTRACT(YEAR FROM SYSDATE)
WHERE o.order_id IS NULL;

-- Solution 2

SELECT c.customer_id,
       c.name
FROM customers c
WHERE NOT EXISTS (
      SELECT 1
      FROM orders o
      WHERE o.customer_id = c.customer_id
      AND EXTRACT(YEAR FROM o.order_date) =
          EXTRACT(YEAR FROM SYSDATE)
);

/*
Interview Note:
NOT EXISTS is commonly preferred for anti-join requirements.
*/

/* ============================================================
SECTION 2: GROUP BY & HAVING (Q16–Q25)
============================================================ */

/* -----------------------------
Q16. Average Salary by Department

Problem:
Calculate the average salary for each department.
------------------------------*/

-- Solution 1

SELECT department,
       ROUND(AVG(salary), 2) AS avg_salary
FROM employees
GROUP BY department;

-- Solution 2

SELECT department,
       SUM(salary) / COUNT(*) AS avg_salary
FROM employees
GROUP BY department;

/*
Interview Note:
AVG() is preferred and more readable.
Know that AVG = SUM / COUNT conceptually.
*/


/* -----------------------------
Q17. Departments With Average Salary Above 60000

Problem:
Identify departments where the average employee salary exceeds ₹60,000.
------------------------------*/

-- Solution 1

SELECT department,
       AVG(salary) AS avg_salary
FROM employees
GROUP BY department
HAVING AVG(salary) > 60000;

-- Solution 2

SELECT department,
       SUM(salary) / COUNT(*) AS avg_salary
FROM employees
GROUP BY department
HAVING SUM(salary) / COUNT(*) > 60000;

/*
Interview Note:
HAVING filters aggregated results.
WHERE cannot be used here.
*/


/* -----------------------------
Q18. Employee Count by Department

Problem:
Determine the number of employees in each department.
------------------------------*/

-- Solution 1

SELECT department,
       COUNT(*) AS employee_count
FROM employees
GROUP BY department;

-- Solution 2

SELECT department,
       COUNT(employee_id) AS employee_count
FROM employees
GROUP BY department;

/*
Interview Note:
COUNT(*) is generally preferred.
*/


/* -----------------------------
Q19. Departments With More Than 10 Employees

Problem:
Find departments having more than 10 employees.
------------------------------*/

-- Solution 1

SELECT department,
       COUNT(*) AS employee_count
FROM employees
GROUP BY department
HAVING COUNT(*) > 10;

-- Solution 2

SELECT department,
       COUNT(employee_id) AS employee_count
FROM employees
GROUP BY department
HAVING COUNT(employee_id) > 10;


/* -----------------------------
Q20. Revenue by Month

Problem:
Calculate monthly revenue generated from orders.
------------------------------*/

-- Solution 1

SELECT TO_CHAR(order_date, 'YYYY-MM') AS month,
       SUM(order_value) AS revenue
FROM orders
GROUP BY TO_CHAR(order_date, 'YYYY-MM')
ORDER BY month;

-- Solution 2

SELECT TRUNC(order_date, 'MM') AS month_start,
       SUM(order_value) AS revenue
FROM orders
GROUP BY TRUNC(order_date, 'MM')
ORDER BY month_start;

/*
Interview Note:
TRUNC(date,'MM') is often preferred in Oracle reporting.
*/


/* -----------------------------
Q21. Orders Count by Month

Problem:
Find the total number of orders placed each month.
------------------------------*/

-- Solution 1

SELECT TO_CHAR(order_date, 'YYYY-MM') AS month,
       COUNT(*) AS order_count
FROM orders
GROUP BY TO_CHAR(order_date, 'YYYY-MM')
ORDER BY month;

-- Solution 2

SELECT TRUNC(order_date, 'MM') AS month_start,
       COUNT(*) AS order_count
FROM orders
GROUP BY TRUNC(order_date, 'MM')
ORDER BY month_start;


/* -----------------------------
Q22. Cities With More Than 50 Customers

Problem:
Identify cities having more than 50 registered customers.
------------------------------*/

-- Solution 1

SELECT city,
       COUNT(*) AS customer_count
FROM customers
GROUP BY city
HAVING COUNT(*) > 50;

-- Solution 2

SELECT city,
       COUNT(customer_id) AS customer_count
FROM customers
GROUP BY city
HAVING COUNT(customer_id) > 50;


/* -----------------------------
Q23. Customers With More Than 5 Orders

Problem:
Find customers who have placed more than 5 orders.
------------------------------*/

-- Solution 1

SELECT customer_id,
       COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(*) > 5;

-- Solution 2

SELECT customer_id,
       COUNT(order_id) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(order_id) > 5;


/* -----------------------------
Q24. Products Sold in More Than 10 Orders

Problem:
Identify products that appeared in more than 10 orders.
------------------------------*/

-- Solution 1

SELECT product_id,
       COUNT(order_id) AS order_count
FROM sales
GROUP BY product_id
HAVING COUNT(order_id) > 10;

-- Solution 2

SELECT p.product_id,
       p.name,
       COUNT(s.order_id) AS order_count
FROM products p
JOIN sales s
     ON p.product_id = s.product_id
GROUP BY p.product_id,
         p.name
HAVING COUNT(s.order_id) > 10;

/*
Interview Note:
Joining products provides business-friendly output.
*/


/* -----------------------------
Q25. Categories Generating More Than ₹1 Lakh Revenue

Problem:
Find product categories generating revenue above ₹100,000.
------------------------------*/

-- Solution 1

SELECT p.category,
       SUM(s.quantity * p.price) AS revenue
FROM products p
JOIN sales s
     ON p.product_id = s.product_id
GROUP BY p.category
HAVING SUM(s.quantity * p.price) > 100000;

-- Solution 2

SELECT category,
       SUM(revenue) AS total_revenue
FROM (
      SELECT p.category,
             s.quantity * p.price AS revenue
      FROM products p
      JOIN sales s
           ON p.product_id = s.product_id
)
GROUP BY category
HAVING SUM(revenue) > 100000;

/*
Interview Note:
A very common revenue aggregation interview question.
Often extended with TOP categories or percentage contribution.
*/


/* ============================================================
SECTION 3: SUBQUERIES (Q26–Q40)
============================================================ */

/* -----------------------------
Q26. Employees Earning Above Company Average Salary

Problem:
Find employees whose salary is higher than the company average salary.
------------------------------*/

-- Solution 1: Scalar Subquery

SELECT employee_id,
       name,
       salary
FROM employees
WHERE salary >
      (SELECT AVG(salary)
       FROM employees);

-- Solution 2: CTE

WITH avg_salary_cte AS (
    SELECT AVG(salary) AS avg_salary
    FROM employees
)
SELECT e.employee_id,
       e.name,
       e.salary
FROM employees e
CROSS JOIN avg_salary_cte a
WHERE e.salary > a.avg_salary;

/*
Interview Note:
One of the most common SQL interview questions.
*/


/* -----------------------------
Q27. Employees Earning Above Department Average Salary

Problem:
Find employees whose salary is greater than the average salary
of their department.
------------------------------*/

-- Solution 1: Correlated Subquery

SELECT employee_id,
       name,
       department,
       salary
FROM employees e
WHERE salary >
      (
          SELECT AVG(salary)
          FROM employees
          WHERE department = e.department
      );

-- Solution 2: Inline View

SELECT e.*
FROM employees e
JOIN (
        SELECT department,
               AVG(salary) AS avg_salary
        FROM employees
        GROUP BY department
     ) d
ON e.department = d.department
WHERE e.salary > d.avg_salary;

/*
Interview Note:
Classic correlated subquery question.
*/


/* -----------------------------
Q28. Products Priced Above Average Product Price

Problem:
Find products priced above the average product price.
------------------------------*/

-- Solution 1

SELECT product_id,
       name,
       price
FROM products
WHERE price >
      (
          SELECT AVG(price)
          FROM products
      );

-- Solution 2

WITH avg_price AS (
     SELECT AVG(price) avg_price
     FROM products
)
SELECT p.*
FROM products p
CROSS JOIN avg_price a
WHERE p.price > a.avg_price;


/* -----------------------------
Q29. Products Priced Below Category Average

Problem:
Find products priced below the average price of their category.
------------------------------*/

-- Solution 1

SELECT product_id,
       name,
       category,
       price
FROM products p
WHERE price <
      (
          SELECT AVG(price)
          FROM products
          WHERE category = p.category
      );

-- Solution 2

SELECT p.*
FROM products p
JOIN (
      SELECT category,
             AVG(price) avg_price
      FROM products
      GROUP BY category
) a
ON p.category = a.category
WHERE p.price < a.avg_price;


/* -----------------------------
Q30. Highest Paid Employee

Problem:
Find the highest paid employee in the company.
------------------------------*/

-- Solution 1

SELECT employee_id,
       name,
       salary
FROM employees
WHERE salary =
      (
          SELECT MAX(salary)
          FROM employees
      );

-- Solution 2

SELECT *
FROM (
      SELECT employee_id,
             name,
             salary,
             DENSE_RANK() OVER
             (ORDER BY salary DESC) rnk
      FROM employees
)
WHERE rnk = 1;

/*
Interview Note:
Expect follow-up:
"What if multiple employees have the same salary?"
*/


/* -----------------------------
Q31. Highest Paid Employee in Each Department

Problem:
Find the highest paid employee in every department.
------------------------------*/

-- Solution 1

SELECT employee_id,
       name,
       department,
       salary
FROM employees e
WHERE salary =
      (
          SELECT MAX(salary)
          FROM employees
          WHERE department = e.department
      );

-- Solution 2

SELECT *
FROM (
      SELECT employee_id,
             name,
             department,
             salary,
             DENSE_RANK() OVER
             (PARTITION BY department
              ORDER BY salary DESC) rnk
      FROM employees
)
WHERE rnk = 1;

/*
Interview Note:
A favorite interviewer question.
*/


/* -----------------------------
Q32. Customer With Highest Total Spend

Problem:
Identify the customer who spent the most overall.
------------------------------*/

-- Solution 1

SELECT customer_id,
       SUM(order_value) total_spend
FROM orders
GROUP BY customer_id
HAVING SUM(order_value) =
(
    SELECT MAX(total_spend)
    FROM (
        SELECT SUM(order_value) total_spend
        FROM orders
        GROUP BY customer_id
    )
);

-- Solution 2

SELECT *
FROM (
      SELECT customer_id,
             SUM(order_value) total_spend,
             DENSE_RANK() OVER
             (ORDER BY SUM(order_value) DESC) rnk
      FROM orders
      GROUP BY customer_id
)
WHERE rnk = 1;


/* -----------------------------
Q33. Most Expensive Product in Each Category

Problem:
Find the most expensive product within each category.
------------------------------*/

-- Solution 1

SELECT product_id,
       name,
       category,
       price
FROM products p
WHERE price =
(
    SELECT MAX(price)
    FROM products
    WHERE category = p.category
);

-- Solution 2

SELECT *
FROM (
      SELECT p.*,
             DENSE_RANK() OVER
             (PARTITION BY category
              ORDER BY price DESC) rnk
      FROM products p
)
WHERE rnk = 1;


/* -----------------------------
Q34. Orders Above Average Order Value

Problem:
Find orders whose value exceeds the average order value.
------------------------------*/

-- Solution 1

SELECT *
FROM orders
WHERE order_value >
(
    SELECT AVG(order_value)
    FROM orders
);

-- Solution 2

WITH avg_order AS (
     SELECT AVG(order_value) avg_value
     FROM orders
)
SELECT o.*
FROM orders o
CROSS JOIN avg_order a
WHERE o.order_value > a.avg_value;


/* -----------------------------
Q35. Customers Spending Above Average Customer Spend

Problem:
Find customers whose total spend is greater than the average
customer spend.
------------------------------*/

-- Solution 1

SELECT customer_id,
       SUM(order_value) total_spend
FROM orders
GROUP BY customer_id
HAVING SUM(order_value) >
(
    SELECT AVG(total_spend)
    FROM (
          SELECT SUM(order_value) total_spend
          FROM orders
          GROUP BY customer_id
    )
);

-- Solution 2

WITH customer_spend AS (
     SELECT customer_id,
            SUM(order_value) total_spend
     FROM orders
     GROUP BY customer_id
)
SELECT *
FROM customer_spend
WHERE total_spend >
(
      SELECT AVG(total_spend)
      FROM customer_spend
);


/* -----------------------------
Q36. Products Sold More Than Average Quantity

Problem:
Find products whose total quantity sold is above average.
------------------------------*/

-- Solution 1

SELECT product_id,
       SUM(quantity) total_qty
FROM sales
GROUP BY product_id
HAVING SUM(quantity) >
(
    SELECT AVG(total_qty)
    FROM (
          SELECT SUM(quantity) total_qty
          FROM sales
          GROUP BY product_id
    )
);

-- Solution 2

WITH product_qty AS (
     SELECT product_id,
            SUM(quantity) total_qty
     FROM sales
     GROUP BY product_id
)
SELECT *
FROM product_qty
WHERE total_qty >
(
      SELECT AVG(total_qty)
      FROM product_qty
);


/* -----------------------------
Q37. Cities Generating Above Average Revenue

Problem:
Find cities whose total revenue exceeds average city revenue.
------------------------------*/

-- Solution 1

SELECT c.city,
       SUM(o.order_value) revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.city
HAVING SUM(o.order_value) >
(
    SELECT AVG(revenue)
    FROM (
          SELECT SUM(o.order_value) revenue
          FROM customers c
          JOIN orders o
          ON c.customer_id = o.customer_id
          GROUP BY c.city
    )
);

-- Solution 2

WITH city_revenue AS (
     SELECT c.city,
            SUM(o.order_value) revenue
     FROM customers c
     JOIN orders o
          ON c.customer_id = o.customer_id
     GROUP BY c.city
)
SELECT *
FROM city_revenue
WHERE revenue >
(
      SELECT AVG(revenue)
      FROM city_revenue
);


/* -----------------------------
Q38. Departments With Maximum Employee Count

Problem:
Find department(s) having the highest employee count.
------------------------------*/

-- Solution 1

SELECT department,
       COUNT(*) employee_count
FROM employees
GROUP BY department
HAVING COUNT(*) =
(
    SELECT MAX(emp_count)
    FROM (
          SELECT COUNT(*) emp_count
          FROM employees
          GROUP BY department
    )
);

-- Solution 2

SELECT *
FROM (
      SELECT department,
             COUNT(*) employee_count,
             DENSE_RANK() OVER
             (ORDER BY COUNT(*) DESC) rnk
      FROM employees
      GROUP BY department
)
WHERE rnk = 1;


/* -----------------------------
Q39. Latest Order in the System

Problem:
Find the most recent order placed in the system.
------------------------------*/

-- Solution 1

SELECT *
FROM orders
WHERE order_date =
(
    SELECT MAX(order_date)
    FROM orders
);

-- Solution 2

SELECT *
FROM (
      SELECT o.*,
             DENSE_RANK() OVER
             (ORDER BY order_date DESC) rnk
      FROM orders o
)
WHERE rnk = 1;


/* -----------------------------
Q40. Earliest Customer Signup

Problem:
Identify the customer(s) who signed up first.
------------------------------*/

-- Solution 1

SELECT *
FROM customers
WHERE signup_date =
(
    SELECT MIN(signup_date)
    FROM customers
);

-- Solution 2

SELECT *
FROM (
      SELECT c.*,
             DENSE_RANK() OVER
             (ORDER BY signup_date) rnk
      FROM customers c
)
WHERE rnk = 1;

/*
Interview Note:
MAX/MIN per group and top-N style questions appear very frequently
in analyst interviews.
*/

/* ============================================================
SECTION 4: CASE STATEMENTS (Q41–Q50)
============================================================ */

/* -----------------------------
Q41. Customer Active/Inactive Classification

Problem:
Classify customers as Active or Inactive based on the is_active flag.
------------------------------*/

-- Solution 1

SELECT customer_id,
       name,
       CASE
           WHEN is_active = 'Y' THEN 'Active'
           ELSE 'Inactive'
       END AS customer_status
FROM customers;

-- Solution 2

SELECT customer_id,
       name,
       DECODE(is_active,
              'Y', 'Active',
              'Inactive') AS customer_status
FROM customers;

/*
Interview Note:
CASE is ANSI SQL standard.
DECODE is Oracle-specific.
*/


/* -----------------------------
Q42. Salary Band Classification

Problem:
Classify employees into salary bands for compensation analysis.
------------------------------*/

-- Solution 1

SELECT employee_id,
       name,
       salary,
       CASE
           WHEN salary < 40000 THEN 'Low'
           WHEN salary BETWEEN 40000 AND 70000 THEN 'Medium'
           ELSE 'High'
       END AS salary_band
FROM employees;

-- Solution 2

SELECT employee_id,
       name,
       salary,
       CASE
           WHEN salary >= 70001 THEN 'High'
           WHEN salary >= 40000 THEN 'Medium'
           ELSE 'Low'
       END AS salary_band
FROM employees;


/* -----------------------------
Q43. Product Price Segmentation

Problem:
Segment products into budget, mid-range and premium categories.
------------------------------*/

-- Solution 1

SELECT product_id,
       name,
       price,
       CASE
           WHEN price < 500 THEN 'Budget'
           WHEN price <= 2000 THEN 'Mid-Range'
           ELSE 'Premium'
       END AS price_segment
FROM products;

-- Solution 2

SELECT product_id,
       name,
       price,
       CASE
           WHEN price > 2000 THEN 'Premium'
           WHEN price >= 500 THEN 'Mid-Range'
           ELSE 'Budget'
       END AS price_segment
FROM products;


/* -----------------------------
Q44. Order Value Segmentation

Problem:
Categorize orders based on order value.
------------------------------*/

-- Solution 1

SELECT order_id,
       order_value,
       CASE
           WHEN order_value < 1000 THEN 'Small Order'
           WHEN order_value <= 5000 THEN 'Medium Order'
           ELSE 'Large Order'
       END AS order_segment
FROM orders;

-- Solution 2

SELECT order_id,
       order_value,
       CASE
           WHEN order_value > 5000 THEN 'Large Order'
           WHEN order_value >= 1000 THEN 'Medium Order'
           ELSE 'Small Order'
       END AS order_segment
FROM orders;


/* -----------------------------
Q45. Customer Spending Tiers

Problem:
Classify customers into spending tiers based on lifetime spend.
------------------------------*/

-- Solution 1

SELECT customer_id,
       total_spend,
       CASE
           WHEN total_spend < 10000 THEN 'Bronze'
           WHEN total_spend <= 50000 THEN 'Silver'
           ELSE 'Gold'
       END AS spending_tier
FROM (
      SELECT customer_id,
             SUM(order_value) AS total_spend
      FROM orders
      GROUP BY customer_id
);

-- Solution 2

WITH customer_spend AS (
     SELECT customer_id,
            SUM(order_value) total_spend
     FROM orders
     GROUP BY customer_id
)
SELECT customer_id,
       total_spend,
       CASE
           WHEN total_spend > 50000 THEN 'Gold'
           WHEN total_spend >= 10000 THEN 'Silver'
           ELSE 'Bronze'
       END AS spending_tier
FROM customer_spend;


/* -----------------------------
Q46. Revenue Bucket Analysis

Problem:
Classify orders into revenue buckets for reporting.
------------------------------*/

-- Solution 1

SELECT order_id,
       order_value,
       CASE
           WHEN order_value < 500 THEN 'Low Revenue'
           WHEN order_value <= 2000 THEN 'Medium Revenue'
           ELSE 'High Revenue'
       END AS revenue_bucket
FROM orders;

-- Solution 2

SELECT order_id,
       order_value,
       CASE
           WHEN order_value > 2000 THEN 'High Revenue'
           WHEN order_value >= 500 THEN 'Medium Revenue'
           ELSE 'Low Revenue'
       END AS revenue_bucket
FROM orders;


/* -----------------------------
Q47. Employee Compensation Grading

Problem:
Assign employee compensation grades based on salary.
------------------------------*/

-- Solution 1

SELECT employee_id,
       name,
       salary,
       CASE
           WHEN salary >= 100000 THEN 'Grade A'
           WHEN salary >= 70000 THEN 'Grade B'
           WHEN salary >= 40000 THEN 'Grade C'
           ELSE 'Grade D'
       END AS compensation_grade
FROM employees;

-- Solution 2

SELECT employee_id,
       name,
       salary,
       CASE
           WHEN salary < 40000 THEN 'Grade D'
           WHEN salary < 70000 THEN 'Grade C'
           WHEN salary < 100000 THEN 'Grade B'
           ELSE 'Grade A'
       END AS compensation_grade
FROM employees;


/* -----------------------------
Q48. Product Category Labeling

Problem:
Create business labels for product categories.
------------------------------*/

-- Solution 1

SELECT product_id,
       name,
       category,
       CASE
           WHEN category = 'Electronics'
                THEN 'Technology'
           WHEN category = 'Clothing'
                THEN 'Fashion'
           WHEN category = 'Furniture'
                THEN 'Home'
           ELSE 'Other'
       END AS category_label
FROM products;

-- Solution 2

SELECT product_id,
       name,
       category,
       DECODE(category,
              'Electronics', 'Technology',
              'Clothing', 'Fashion',
              'Furniture', 'Home',
              'Other') AS category_label
FROM products;

/*
Interview Note:
CASE is preferred for complex mappings.
*/


/* -----------------------------
Q49. Customer Loyalty Status

Problem:
Assign loyalty status based on number of orders placed.
------------------------------*/

-- Solution 1

SELECT customer_id,
       total_orders,
       CASE
           WHEN total_orders >= 20 THEN 'Platinum'
           WHEN total_orders >= 10 THEN 'Gold'
           WHEN total_orders >= 5 THEN 'Silver'
           ELSE 'Regular'
       END AS loyalty_status
FROM (
      SELECT customer_id,
             COUNT(*) total_orders
      FROM orders
      GROUP BY customer_id
);

-- Solution 2

WITH customer_orders AS (
     SELECT customer_id,
            COUNT(*) total_orders
     FROM orders
     GROUP BY customer_id
)
SELECT customer_id,
       total_orders,
       CASE
           WHEN total_orders < 5 THEN 'Regular'
           WHEN total_orders < 10 THEN 'Silver'
           WHEN total_orders < 20 THEN 'Gold'
           ELSE 'Platinum'
       END AS loyalty_status
FROM customer_orders;


/* -----------------------------
Q50. High-Value vs Low-Value Customer Classification

Problem:
Classify customers as High Value or Low Value based on
whether their spending exceeds the average customer spend.
------------------------------*/

-- Solution 1

SELECT customer_id,
       total_spend,
       CASE
           WHEN total_spend >
                (
                  SELECT AVG(total_spend)
                  FROM (
                        SELECT SUM(order_value) total_spend
                        FROM orders
                        GROUP BY customer_id
                  )
                )
           THEN 'High Value'
           ELSE 'Low Value'
       END AS customer_type
FROM (
      SELECT customer_id,
             SUM(order_value) total_spend
      FROM orders
      GROUP BY customer_id
);

-- Solution 2

WITH customer_spend AS (
     SELECT customer_id,
            SUM(order_value) total_spend
     FROM orders
     GROUP BY customer_id
),
avg_spend AS (
     SELECT AVG(total_spend) avg_spend
     FROM customer_spend
)
SELECT c.customer_id,
       c.total_spend,
       CASE
           WHEN c.total_spend > a.avg_spend
                THEN 'High Value'
           ELSE 'Low Value'
       END AS customer_type
FROM customer_spend c
CROSS JOIN avg_spend a;

/*
Interview Note:
Excellent business reporting question.
Combines aggregation, subqueries and CASE statements.
*/
